
author: HelianthusWhite

# html lang
language: en

title: HelianthusWhite

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives
  Contact: /contact
  

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/mytheme.css
- /css/reset.css

# scripts loaded in the end of the body
scripts:
- /js/three.min.js
- /js/projector.js
- /js/canvas-renderer.js
- /js/3d-lines-animation.js
- /js/mytheme.js

photo: /img/photo.jpg



